allowBuilds:
  esbuild: true
  spawn-sync: true
  unrs-resolver: true

autoInstallPeers: true

enablePrePostScripts: true

engineStrict: true

minimumReleaseAge: 2880 # 2 days

minimumReleaseAgeExclude:
  - '@webdeveric/utils@0.78.0'
