allowBuilds:
  esbuild: true
  spawn-sync: true
  unrs-resolver: true

autoInstallPeers: true

enablePrePostScripts: true

engineStrict: true

minimumReleaseAge: 2880 # 2 days

minimumReleaseAgeExclude:
  - "@webdeveric/prettier-config@0.4.0"
  - "@webdeveric/utils@0.76.0"
